const translations = {
  'general.add': 'Add',
  'general.cancel': 'Cancel',
  'general.confirm': 'Confirm',
  'general.save': 'Save',
  'appBar.menu': 'Menu',
  'appBar.signIn': 'Sign in',
  'appBar.signOut': 'Sign out',
  'menu.chapters': 'Chapters',
  'menu.words': 'Words',
  'signIn.email': 'Email',
  'signIn.password': 'Password',
  'signIn.submit': 'Sign in',
  'errors.userNotFound': 'There is no user with this email',
  'errors.wrongPassword': 'Entered password is invalid',
  'errors.invalidEmail': 'Entered email is not correct',
  'chapters.title': 'Chapters',
  'chapter.name': 'Chapter\'s name',
  'chapter.new': 'New chapter',
  'chapter.deleteConfirmation': 'Deleting chapter will remove all related words. Are you sure?',
  'words.add.title': 'Add new words',
  'words.add.input.oneByOne': 'One by one',
  'words.add.input.file': 'From file',
  'words.add.type': 'Type',
  'words.add.type.noun': 'Noun',
  'words.add.type.verb': 'Verb',
  'words.add.type.adjective': 'Adjective',
  'words.add.type.expression': 'Expression',
  'words.add.type.other': 'Other',
  'words.add.hasDifferentForms': 'Different masculine and feminine forms',
  'words.add.hasPreposition': 'With preposition',
  'words.add.hasIrregularPlural': 'Has irregular plural form',
  'words.add.hasPostposition': 'With postposition',
  'words.add.wordInFrench': 'Word in French',
  'words.add.translation': 'English translation',
  'words.add.plural': 'Plural form',
  'words.add.masculine': 'Masculine form',
  'words.add.feminine': 'Feminine form',
  'words.add.gender': 'Gender',
  'words.add.preposition': 'Preposition',
  'words.add.postposition': 'Postposition',
  'words.add.gender.masculine': 'm',
  'words.add.gender.feminine': 'f',
  'words.add.verbGroup': 'Verb group',
  'words.add.additionalInfo': 'Additional info'
};

export default translations;
