const translations = {
  'general.add': 'Add',
  'general.cancel': 'Cancel',
  'general.confirm': 'Confirm',
  'general.save': 'Save',
  'general.next': 'Next',
  'general.yes': 'Yes',
  'general.no': 'No',
  'appBar.menu': 'Menu',
  'appBar.en': 'En',
  'appBar.et': 'Et',
  'appBar.signIn': 'Sign in',
  'appBar.signOut': 'Sign out',
  'menu.home': 'Home',
  'menu.account': 'My account',
  'menu.manageAccounts': 'Manage accounts',
  'menu.chapters': 'Chapters',
  'menu.subjects': 'Subjects',
  'menu.words': 'Words',
  'menu.chapter.words': 'Words',
  'menu.chapter.subjects': 'Subjects',
  'home.title': 'YFA - Your French Assistant',
  'home.intro1': 'Best way to master the vocabulary!',
  'home.intro2': 'This application helps you to learn French words with the necessary elements to make sentences:',
  'home.point1': 'nouns with their gender',
  'home.point2': 'adjectives in masculine and feminine forms',
  'home.point3': 'verbs with their conjugation group and following prepositions',
  'home.outro': 'Once you try the application, you will never go back to your old learning habits!',
  'signIn.email': 'Email',
  'signIn.password': 'Password',
  'signIn.submit': 'Sign in',
  'signIn.forgotPassword': 'Forgot password?',
  'signIn.noAccount': 'Don\'t have an account?',
  'signIn.signUp': 'Sign up',
  'signUp.introMessage': 'Registration is only necessary for lectors in order to be able to insert and manage courses\' vocabulary. By signing up, you are sending an application which has to be confirmed by an administrative lector.',
  'signUp.name': 'Full name',
  'signUp.email': 'Email',
  'signUp.password': 'Password',
  'signUp.confirmPassword': 'Confirm password',
  'signUp.submit': 'Sign up',
  'errors.userNotFound': 'There is no user with this email',
  'errors.wrongPassword': 'Entered password is invalid',
  'errors.invalidEmail': 'Entered email is not correct',
  'errors.weakPassword': 'Password must be at least 8 characters long and contain one upper case letter, one lower case letter, one digit and one special character (#?!@$%^&*-_)',
  'errors.differentPasswords': 'Passwords do not match',
  'errors.emailExists': 'An account with this email address already exists',
  'changePassword.newPassword': 'New password',
  'changePassword.confirmPassword': 'Confirm new password',
  'changePassword.submit': 'Reset password',
  'forgotPassword.email': 'Email address',
  'forgotPassword.reset': 'Reset password',
  'account.notActivated': 'Your account is not activated yet. Please contact course\'s supervisor.',
  'accounts.title': 'Accounts\' management',
  'accounts.noUsers': 'No accounts to show',
  'accounts.name': 'Name',
  'accounts.email': 'Email',
  'accounts.isActive': 'Account active',
  'accounts.isAdmin': 'Admin',
  'accounts.activate': 'Activate',
  'accounts.makeAdministrator': 'Make administrator',
  'chapters.title': 'Chapters',
  'chapter.name': 'Chapter\'s name',
  'chapter.new': 'New chapter',
  'chapter.deleteConfirmation': 'Deleting chapter will remove all related subjects and words. Are you sure?',
  'subjects.noSubjects': 'No subjects have been added under this chapter',
  'subjects.title': 'Subjects',
  'subject.name': 'Subject\'s name',
  'subject.new': 'New subject',
  'subject.chapterName': 'Chapter',
  'subject.deleteConfirmation': 'Deleting subject will remove all related words. Are you sure?',
  'fileUpload.addFile': 'ADD FILE',
  'words.add.title': 'Add new words',
  'words.add.step1': 'Chapter and subject',
  'words.add.step2': 'How to add',
  'words.add.step3': 'Adding and modifying',
  'words.add.input.oneByOne': 'One by one',
  'words.add.input.file': 'From file',
  'words.add.input.file.message': 'You can modify and add words after uploading the file',
  'words.add.input.file.example': 'File must have given structure. Look example file',
  'words.add.chapter': 'Chapter',
  'words.add.subject': 'Subject',
  'words.add.cardTitle': 'New word',
  'words.add.cardEditTitle': 'Edit word',
  'words.add.type': 'Type',
  'words.add.type.noun': 'Noun',
  'words.add.type.verb': 'Verb',
  'words.add.type.adjective': 'Adjective',
  'words.add.type.expression': 'Expression',
  'words.add.type.other': 'Other',
  'words.add.hasDifferentForms': 'Different masculine and feminine forms',
  'words.add.hasPreposition': 'With preposition',
  'words.add.hasIrregularPlural': 'Has irregular plural form',
  'words.add.hasPostposition': 'With postposition',
  'words.add.wordInFrench': 'Word in French',
  'words.add.translation': 'English translation',
  'words.add.plural': 'Plural form',
  'words.add.masculine': 'Masculine form',
  'words.add.feminine': 'Feminine form',
  'words.add.gender': 'Gender',
  'words.add.preposition': 'Preposition',
  'words.add.postposition': 'Postposition',
  'words.add.gender.masculine': 'm',
  'words.add.gender.feminine': 'f',
  'words.add.verbGroup': 'Verb group',
  'words.add.additionalInfo': 'Additional info',
  'addedWords.french': 'French',
  'addedWords.masculine': 'Masculine',
  'addedWords.feminine': 'Feminine',
  'addedWords.english': 'English',
  'addedWords.type': 'Type',
  'addedWords.gender': 'Gender',
  'addedWords.plural': 'Plural',
  'addedWords.preposition': 'Preposition',
  'addedWords.postposition': 'Postposition',
  'addedWords.verbGroup': 'Group',
  'addedWords.additionalInfo': 'Info',
  'words.list.expandCards': 'Expand all words',
  'words.list.sortBy': 'Sort by',
  'words.list.sortByFrench': 'French',
  'words.list.sortByEnglish': 'English',
  'words.list.sortByRandom': 'Random',
  'words.list.type': 'Type',
  'words.list.wordInFrench': 'Word in French',
  'words.list.masculine': 'Masculine form',
  'words.list.feminine': 'Feminine form',
  'words.list.plural': 'Plural form',
  'words.list.gender': 'Gender',
  'words.list.translation': 'Word in English',
  'words.list.preposition': 'Preposition',
  'words.list.postposition': 'Postposition',
  'words.list.verbGroup': 'Verb group',
  'words.list.additionalInfo': 'Additional info',
  'words.list.translate': 'Test knowledge',
  'word.translate.french': 'French',
  'word.translate.masculine': 'Masculine form',
  'word.translate.feminine': 'Feminine form',
  'word.translate.plural': 'Plural',
  'word.translate.gender': 'Gender',
  'word.translate.preposition': 'Preposition',
  'word.translate.postposition': 'Postposition',
  'word.translate.verbGroup': 'Verb group',
  'word.translate.check': 'Check',
  'word.translate.translateAgain': 'Translate again',
  'word.translate.back': 'Back to words list'
};

export default translations;
