const translations = {
  'general.add': 'Lisa',
  'general.cancel': 'Katkesta',
  'general.confirm': 'Kinnita',
  'general.save': 'Salvesta',
  'general.next': 'Järgmine',
  'appBar.menu': 'Menüü',
  'appBar.signIn': 'Logi sisse',
  'appBar.signOut': 'Logi välja',
  'menu.chapters': 'Peatükid',
  'menu.words': 'Sõnad',
  'menu.subjects': 'Teemad',
  'menu.chapter.words': 'Sõnad',
  'menu.chapter.subjects': 'Teemad',
  'signIn.email': 'E-post',
  'signIn.password': 'Parool',
  'signIn.submit': 'Logi sisse',
  'errors.userNotFound': 'Sellise e-posti aadressiga kasutajat ei leitud',
  'errors.wrongPassword': 'Sisestatud parool on vale',
  'errors.invalidEmail': 'Sisestatud e-posti aadress on vigane',
  'chapters.title': 'Peatükid',
  'chapter.name': 'Peatüki nimi',
  'chapter.new': 'Uus peatükk',
  'chapter.deleteConfirmation': 'Peatüki kustutamine kustutab ka kõik sellega seotud teemad ja sõnad. Kas oled kindel?',
  'subjects.title': 'Teemad',
  'subject.name': 'Teema nimi',
  'subject.new': 'Uus teema',
  'subject.chapterName': 'Peatükk',
  'subject.deleteConfirmation': 'Teema kustutamine kustutab ka kõik sellega seotud sõnad. Kas oled kindel?',
  'fileUpload.addFile': 'LISA FAIL',
  'words.add.title': 'Uute sõnade lisamine',
  'words.add.step1': 'Peatükk ja teema',
  'words.add.step2': 'Kuidas lisada',
  'words.add.step3': 'Lisamine ja muutmine',
  'words.add.input.oneByOne': 'Ühekaupa',
  'words.add.input.file': 'Failist',
  'words.add.input.file.message': 'Pärast faili üleslaadimist on võimalik sõnu muuta ning lisada',
  'words.add.chapter': 'Peatükk',
  'words.add.subject': 'Teema',
  'words.add.cardTitle': 'Uus sõna',
  'words.add.cardEditTitle': 'Muuda sõna',
  'words.add.type': 'Sõnaliik',
  'words.add.type.noun': 'Nimisõna',
  'words.add.type.verb': 'Tegusõna',
  'words.add.type.adjective': 'Omadussõna',
  'words.add.type.expression': 'Väljend',
  'words.add.type.other': 'Muu',
  'words.add.hasDifferentForms': 'Erinevad mees- ja naissoo vormid',
  'words.add.hasPreposition': 'Eessõnaga',
  'words.add.hasIrregularPlural': 'Ebareeglipärane mitmus',
  'words.add.hasPostposition': 'Järelsõnaga',
  'words.add.wordInFrench': 'Prantsuskeelne sõna',
  'words.add.translation': 'Ingliskeelne tõlge',
  'words.add.plural': 'Mitmuse vorm',
  'words.add.masculine': 'Meessoo vorm',
  'words.add.feminine': 'Naissoo vorm',
  'words.add.gender': 'Sugu',
  'words.add.preposition': 'Eessõna',
  'words.add.postposition': 'Järelsõna',
  'words.add.gender.masculine': 'm',
  'words.add.gender.feminine:': 'f',
  'words.add.verbGroup': 'Tegusõna grupp',
  'words.add.additionalInfo': 'Lisainfo',
  'addedWords.french': 'Prantsusk.',
  'addedWords.masculine': 'Meess.',
  'addedWords.feminine': 'Naiss.',
  'addedWords.english': 'Inglisk.',
  'addedWords.type': 'Sõnaliik',
  'addedWords.gender': 'Sugu',
  'addedWords.plural': 'Mitmus',
  'addedWords.preposition': 'Eessõna',
  'addedWords.postposition': 'Järelsõna',
  'addedWords.verbGroup': 'Grupp',
  'addedWords.additionalInfo': 'Info',
  'words.list.expandCards': 'Ava kõik sõnakaardid',
  'words.list.sortBy': 'Sorteerimine:',
  'words.list.sortByFrench': 'Prantsuse keel',
  'words.list.sortByEnglish': 'Inglise keel',
  'words.list.sortByRandom': 'Juhuslik',
  'words.list.type': 'Sõnaliik',
  'words.list.wordInFrench': 'Prantsuskeelne sõna',
  'words.list.masculine': 'Messoo vorm',
  'words.list.feminine': 'Naissoo vorm',
  'words.list.plural': 'Mitmuse vorm',
  'words.list.gender': 'Sugu',
  'words.list.translation': 'Ingliskeelne tõlge',
  'words.list.preposition': 'Eessõna',
  'words.list.postposition': 'Järelsõna',
  'words.list.verbGroup': 'Tegusõna grupp',
  'words.list.additionalInfo': 'Lisainfo',
  'words.list.translate': 'Testi teadmisi'
};

export default translations;
