const translations = {
  'general.add': 'Lisa',
  'general.cancel': 'Katkesta',
  'general.confirm': 'Kinnita',
  'general.save': 'Salvesta',
  'general.next': 'Järgmine',
  'general.yes': 'Jah',
  'general.no': 'Ei',
  'appBar.menu': 'Menüü',
  'appBar.en': 'En',
  'appBar.et': 'Et',
  'appBar.signIn': 'Logi sisse',
  'appBar.signOut': 'Logi välja',
  'menu.home': 'Avaleht',
  'menu.account': 'Minu konto',
  'menu.manageAccounts': 'Kontode haldamine',
  'menu.chapters': 'Peatükid',
  'menu.words': 'Sõnad',
  'menu.subjects': 'Teemad',
  'menu.chapter.words': 'Sõnad',
  'menu.chapter.subjects': 'Teemad',
  'home.title': 'YFA - Your French Assistant',
  'home.intro1': 'Parim viis sõnavara omandamiseks!',
  'home.intro2': 'See rakendus aitab sul õppida prantuse keele sõnavara koos vajalike elementidega, et luua lauseid:',
  'home.point1': 'nimisõnad koos sooga',
  'home.point2': 'omadussõnad nii meessoost kui ka naissoost vormis',
  'home.point3': 'tegusõnad koos pöördkonna ja järgnevate eessõnadega',
  'home.outro': 'Kui oled kord YFA rakendust proovinud, ei soovi sa enam kunagi endiste õpimeetodite juurde tagasi minna!',
  'signIn.email': 'E-post',
  'signIn.password': 'Parool',
  'signIn.submit': 'Logi sisse',
  'signIn.forgotPassword': 'Unustasid parooli?',
  'signIn.noAccount': 'Pole kontot?',
  'signIn.signUp': 'Registreeru',
  'signUp.introMessage': 'Registreerumine on vajalik õppejõududele, et sisestada ja hallata kursuste sõnavara. Registreerudes saadad taotluse, mille peab kinnitama administreeriv õppejõud.',
  'signUp.name': 'Täisnimi',
  'signUp.email': 'E-post',
  'signUp.password': 'Parool',
  'signUp.confirmPassword': 'Kinnita parooli',
  'signUp.submit': 'Registreeru',
  'errors.userNotFound': 'Sellise e-posti aadressiga kasutajat ei leitud',
  'errors.wrongPassword': 'Sisestatud parool on vale',
  'errors.invalidEmail': 'Sisestatud e-posti aadress on vigane',
  'errors.weakPassword': 'Parool peab olema vähemalt 8 sümbolit pikk ning sisaldama üht väike- ning suurtähte, üht numbrit ja üht erisümbolit (#?!@$%^&*-_)',
  'errors.differentPasswords': 'Paroolid ei kattu',
  'errors.emailExists': 'Sellise e-posti aadressiga konto on juba loodud',
  'changePassword.newPassword': 'Uus parool',
  'changePassword.confirmPassword': 'Kinnita uus parool',
  'changePassword.submit': 'Muuda parooli',
  'forgotPassword.email': 'E-posti aadress',
  'forgotPassword.reset': 'Lähtesta parool',
  'account.notActivated': 'Sinu konto ei ole veel aktiveeritud. Palun võta ühendust kursust administreeriva õppejõuga.',
  'accounts.title': 'Kontode haldamine',
  'accounts.noUsers': 'Kontod puuduvad',
  'accounts.name': 'Nimi',
  'accounts.email': 'E-post',
  'accounts.isActive': 'Kasutaja aktiivne',
  'accounts.isAdmin': 'Administraator',
  'accounts.activate': 'Aktiveeri',
  'accounts.makeAdministrator': 'Tee administraatoriks',
  'chapters.title': 'Peatükid',
  'chapter.name': 'Peatüki nimi',
  'chapter.new': 'Uus peatükk',
  'chapter.deleteConfirmation': 'Peatüki kustutamine kustutab ka kõik sellega seotud teemad ja sõnad. Kas oled kindel?',
  'subjects.noSubjects': 'Selle peatüki alla pole veel teemasid lisatud',
  'subjects.title': 'Teemad',
  'subject.name': 'Teema nimi',
  'subject.new': 'Uus teema',
  'subject.chapterName': 'Peatükk',
  'subject.deleteConfirmation': 'Teema kustutamine kustutab ka kõik sellega seotud sõnad. Kas oled kindel?',
  'fileUpload.addFile': 'LISA FAIL',
  'words.add.title': 'Sõnade lisamine ja muutmine',
  'words.add.step1': 'Peatükk ja teema',
  'words.add.step2': 'Kuidas lisada',
  'words.add.step3': 'Lisamine ja muutmine',
  'words.add.input.oneByOne': 'Ühekaupa',
  'words.add.input.file': 'Failist',
  'words.add.input.file.message': 'Pärast faili üleslaadimist on võimalik sõnu muuta ning lisada',
  'words.add.input.file.example': 'Failil peab olema etteantud struktuur. Vaata näidisfaili. Ole kindel, et sinu failis on ainult üks lehekülg!',
  'words.add.chapter': 'Peatükk',
  'words.add.subject': 'Teema',
  'words.add.cardTitle': 'Uus sõna',
  'words.add.cardEditTitle': 'Muuda sõna',
  'words.add.type': 'Sõnaliik',
  'words.add.type.noun': 'Nimisõna',
  'words.add.type.verb': 'Tegusõna',
  'words.add.type.adjective': 'Omadussõna',
  'words.add.type.expression': 'Väljend',
  'words.add.type.other': 'Muu',
  'words.add.hasDifferentForms': 'Erinevad mees- ja naissoo vormid',
  'words.add.hasPreposition': 'Eessõnaga',
  'words.add.hasIrregularPlural': 'Ebareeglipärane mitmus',
  'words.add.wordInFrench': 'Prantsuskeelne sõna',
  'words.add.translation': 'Ingliskeelne tõlge',
  'words.add.plural': 'Mitmuse vorm',
  'words.add.masculine': 'Meessoo vorm',
  'words.add.feminine': 'Naissoo vorm',
  'words.add.gender': 'Sugu',
  'words.add.preposition': 'Eessõna',
  'words.add.gender.masculine': 'm',
  'words.add.gender.feminine:': 'f',
  'words.add.gender.feminineMasculine': 'm/f',
  'words.add.gender.feminine.plural': 'f/pl',
  'words.add.gender.masculine.plural': 'm/pl',
  'words.add.verbGroup': 'Grupp',
  'words.add.additionalInfo': 'Lisainfo',
  'addedWords.french': 'Prantsusk.',
  'addedWords.masculine': 'Meess.',
  'addedWords.feminine': 'Naiss.',
  'addedWords.english': 'Inglisk.',
  'addedWords.type': 'Sõnaliik',
  'addedWords.gender': 'Sugu',
  'addedWords.plural': 'Mitmus',
  'addedWords.preposition': 'Eessõna',
  'addedWords.verbGroup': 'Grupp',
  'addedWords.additionalInfo': 'Info',
  'words.list.noWords': 'Sõnu ei ole veel lisatud',
  'words.list.expandCards': 'Ava kõik sõnakaardid',
  'words.list.sortBy': 'Sorteeri:',
  'words.list.sortByFrench': 'Pr. k.',
  'words.list.sortByEnglish': 'Ingl. k.',
  'words.list.sortByRandom': 'Juhuslik',
  'words.list.type': 'Sõnaliik',
  'words.list.wordInFrench': 'Prantsuskeelne sõna',
  'words.list.masculine': 'Messoo vorm',
  'words.list.feminine': 'Naissoo vorm',
  'words.list.plural': 'Mitmuse vorm',
  'words.list.gender': 'Sugu',
  'words.list.translation': 'Ingliskeelne tõlge',
  'words.list.preposition': 'Eessõna',
  'words.list.verbGroup': 'Tegusõna grupp',
  'words.list.additionalInfo': 'Lisainfo',
  'words.list.translate': 'Testi teadmisi',
  'word.translate.french': 'Prantsuskeelne sõna',
  'word.translate.masculine': 'Meessoo vorm',
  'word.translate.feminine': 'Naissoo vorm',
  'word.translate.plural': 'Mitmuse vorm',
  'word.translate.gender': 'Sugu',
  'word.translate.preposition': 'Eessõna',
  'word.translate.verbGroup': 'Tegusõna grupp',
  'word.translate.check': 'Kontrolli',
  'word.translate.translateAgain': 'Tõlgi algusest',
  'word.translate.back': 'Tagasi nimekirja'
};

export default translations;
